#!/usr/bin/env python3
"""
生成专四 / 专八义项表 Excel（格式对齐 senses_table.xlsx），并附配图提示词。

输出:
  data/content/senses_table_tem4.xlsx
  data/content/senses_table_tem8.xlsx
  data/content/senses_table_exams.xlsx   # 双表合订 + 说明

用法:
  python3 scripts/build_exam_senses_xlsx.py
"""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "content"

HEADERS = [
    "西语",
    "义项",
    "categoría",
    "级别",
    "中文释义",
    "例句*西语",
    "例句*中文",
    "图片",
    "配图提示词",
]

# ── 配图提示词（统一风格，同学 B 可直接粘贴到 AI 绘图工具）────────────
PROMPT_PREFIX = (
    "教育插画风格，正方形 1:1 构图，明亮柔和色调，单一清晰主体，"
    "浅色干净背景，无文字、无水印、无 logo。"
)


def prompt(scene: str) -> str:
    return f"{PROMPT_PREFIX}画面表现：{scene}"


# (lemma, sense, cat, level, zh, es, zh_ex, scene)
# cat: f/m/v/adj/adv …
TEM4: list[tuple] = [
    (
        "matrícula",
        1,
        "f",
        "A2",
        "注册；学籍注册",
        "Antes del semestre debes completar la matrícula en la web de la universidad y pagar las tasas a tiempo.",
        "学期开始前，你必须在学校网站上完成注册并按时缴纳学费。",
        "一位大学生在笔记本电脑前填写在线注册表格，桌上放着学生证和笔记本",
    ),
    (
        "asignatura",
        1,
        "f",
        "A2",
        "课程；科目",
        "Mi asignatura favorita es literatura española porque leemos textos interesantes y debatimos en clase.",
        "我最喜欢的科目是西班牙文学，因为我们会读有趣的文本并在课上讨论。",
        "大学教室里黑板上写着课程名称，桌上摊开几本教科书",
    ),
    (
        "horario",
        1,
        "m",
        "A2",
        "时间表；课表",
        "Según mi horario, tengo clase de gramática por la mañana y taller de conversación por la tarde.",
        "根据我的课表，上午有语法课，下午有口语工作坊。",
        "一张彩色周课表贴在墙上，旁边有时钟和书包",
    ),
    (
        "biblioteca",
        1,
        "f",
        "A2",
        "图书馆",
        "Paso muchas tardes en la biblioteca repasando vocabulario y preparando los exámenes de español.",
        "我许多个下午都在图书馆复习词汇、准备西班牙语考试。",
        "安静的大学图书馆内景，书架、阅读灯与埋头学习的学生",
    ),
    (
        "apuntes",
        1,
        "m",
        "A2",
        "笔记（常用复数）",
        "Después de clase organizo mis apuntes con colores para recordar mejor las reglas de conjugación.",
        "下课后我会用颜色整理笔记，以便更好地记住变位规则。",
        "摊开的笔记本上用彩色笔做重点标注，旁边放着钢笔",
    ),
    (
        "examen",
        1,
        "m",
        "A2",
        "考试",
        "El examen de español incluirá comprensión lectora, redacción corta y un ejercicio de vocabulario.",
        "西语考试将包括阅读理解、短文写作和一道词汇题。",
        "考场里学生安静答题，桌上放着试卷和铅笔",
    ),
    (
        "aprobar",
        1,
        "v",
        "A2",
        "通过（考试）",
        "Si estudias cada día un poco, es más fácil aprobar la asignatura sin estudiar todo la noche anterior.",
        "如果你每天学一点，不必考前熬夜也能更容易通过这门课。",
        "学生看到成绩单上合格标记后露出轻松笑容",
    ),
    (
        "suspender",
        1,
        "v",
        "A2",
        "不及格；挂科",
        "Suspendí el primer parcial, pero con tutorías y más práctica de escritura mejoré mucho en el final.",
        "第一次期中我挂了，但通过辅导和更多写作练习，期末进步很大。",
        "学生看着不太理想的成绩，朋友在一旁鼓励他继续努力",
    ),
    (
        "deberes",
        1,
        "m",
        "A2",
        "作业（常用复数）",
        "Los deberes de esta semana son escuchar un podcast y escribir un resumen de cien palabras.",
        "这周的作业是听一段播客，并写一百字左右的摘要。",
        "书桌前学生一边听耳机一边在本子上写作业",
    ),
    (
        "entrega",
        1,
        "f",
        "B1",
        "提交；交作业",
        "La fecha de entrega del ensayo es el viernes; el profesor no acepta trabajos fuera de plazo.",
        "论文提交截止日是周五，老师不接受逾期作业。",
        "学生把装订好的论文放进提交箱或点击电脑上的提交按钮",
    ),
    (
        "ensayo",
        1,
        "m",
        "B1",
        "议论文；散文式写作",
        "En el ensayo debes presentar una tesis clara y apoyarla con ejemplos y argumentos coherentes.",
        "在议论文中你需要提出清晰论点，并用例子与连贯论据加以支持。",
        "书桌上摊开的议论文草稿，旁边有提纲卡片与字典",
    ),
    (
        "resumen",
        1,
        "m",
        "A2",
        "摘要；概要",
        "Primero leo el texto completo y luego escribo un resumen sin copiar frases largas del original.",
        "我先通读全文，再写摘要，并且不照抄原文长句。",
        "一边是长文，一边是写好的短摘要，箭头表示浓缩过程",
    ),
    (
        "traducción",
        1,
        "f",
        "B1",
        "翻译",
        "La traducción no es solo cambiar palabras: hay que respetar el sentido y el tono del texto original.",
        "翻译不只是换词，还要尊重原文的意义与语气。",
        "两页并排：左页西语、右页中文，中间有桥梁式转化示意",
    ),
    (
        "vocabulario",
        1,
        "m",
        "A2",
        "词汇",
        "Ampliar el vocabulario te ayuda a entender mejor las noticias y a expresarte con más precisión.",
        "扩大词汇量能帮你更好地读懂新闻，并更准确地表达自己。",
        "单词卡片散落在桌上，背景是西班牙语书籍",
    ),
    (
        "gramática",
        1,
        "f",
        "A2",
        "语法",
        "Repasamos la gramática del subjuntivo con ejemplos de la vida diaria y no solo con reglas abstractas.",
        "我们用日常生活例句复习虚拟式语法，而不只背抽象规则。",
        "黑板或白板写着简单语法结构，老师指着例句讲解",
    ),
    (
        "conjugación",
        1,
        "f",
        "A2",
        "动词变位",
        "Para dominar la conjugación irregular conviene practicar en voz alta y escribir oraciones nuevas.",
        "要掌握不规则变位，宜出声练习并写出新句子。",
        "动词变位表以表格形式呈现，旁边有一张嘴在练习朗读的示意",
    ),
    (
        "comunicación",
        1,
        "f",
        "B1",
        "交际；沟通",
        "En clase practicamos la comunicación oral con role-plays de viaje, entrevista y presentación.",
        "课上我们用旅行、面试和报告等角色扮演练习口语交际。",
        "两名学生面对面交谈，旁边有对话气泡示意",
    ),
    (
        "intercambio",
        1,
        "m",
        "B1",
        "（语言）交换；交流",
        "Hago un intercambio lingüístico con un estudiante español: yo practico español y él practica chino.",
        "我和一位西班牙学生做语言交换：我练西语，他练中文。",
        "两位不同国家的年轻人在咖啡馆交流，桌上放着笔记本",
    ),
    (
        "cultura",
        1,
        "f",
        "A2",
        "文化",
        "Conocer la cultura hispana te ayuda a entender chistes, gestos y referencias en series y películas.",
        "了解西语文化能帮你听懂玩笑、手势以及影视剧里的典故。",
        "西班牙与拉美文化意象拼贴：吉他、头巾、市场与节庆旗帜（无文字）",
    ),
    (
        "costumbre",
        1,
        "f",
        "A2",
        "习俗；习惯",
        "Es costumbre en muchos países hispanos saludar con dos besos entre amigos, aunque varía por región.",
        "许多西语国家朋友间流行贴两下脸颊打招呼，不过各地区有差异。",
        "朋友见面亲切问候的温馨场景，背景是南欧风小街",
    ),
    (
        "tradición",
        1,
        "f",
        "B1",
        "传统",
        "La tradición de las fiestas populares combina música, comida y participación de toda la comunidad.",
        "民间节日传统融合了音乐、美食和全社区的参与。",
        "街道节庆游行：彩带、乐器与庆祝人群，气氛明亮",
    ),
    (
        "sociedad",
        1,
        "f",
        "B1",
        "社会",
        "En la sociedad actual el español se usa en medios, turismo y negocios internacionales cada vez más.",
        "在当今社会，西语越来越多地用于媒体、旅游与国际贸易。",
        "城市天际线下人群穿行，隐约有学校与办公楼剪影",
    ),
    (
        "medio ambiente",
        1,
        "m",
        "B1",
        "环境；生态环境",
        "En el debate hablamos del medio ambiente y de cómo reducir el plástico en la vida cotidiana.",
        "辩论中我们谈了生态环境，以及如何在日常生活中减少塑料。",
        "绿色公园与回收垃圾桶，学生在做环保志愿活动",
    ),
    (
        "noticia",
        1,
        "f",
        "A2",
        "新闻；消息",
        "Cada mañana leo una noticia breve en español para acostumbrarme a estructuras reales del idioma.",
        "我每天早上读一篇西语短新闻，以熟悉真实语言结构。",
        "平板电脑显示简洁新闻版面（无具体文字），旁边一杯咖啡",
    ),
    (
        "artículo",
        1,
        "m",
        "B1",
        "文章；（报刊）文章",
        "El artículo del periódico explica con claridad las causas y consecuencias del cambio climático.",
        "这篇报刊文章清楚地解释了气候变化的原因与后果。",
        "摊开的报纸或杂志特写，聚焦一篇图文并茂的专栏",
    ),
    (
        "entrevista",
        1,
        "f",
        "B1",
        "采访；面试",
        "Para la entrevista de trabajo preparé respuestas sobre mi experiencia y mis objetivos profesionales.",
        "为了工作面试，我准备了关于经历与职业目标的回答。",
        "会议室里两人隔桌交谈，一方做笔记，气氛正式而友好",
    ),
    (
        "presentación",
        1,
        "f",
        "B1",
        "口头报告；演示",
        "En la presentación usa diapositivas simples y habla despacio para que el público entienda tu idea.",
        "做报告时请用简洁幻灯片，语速放慢，好让听众理解你的想法。",
        "学生站在投影屏前做演示，同学们坐在下面听讲",
    ),
    (
        "opinión",
        1,
        "f",
        "A2",
        "观点；意见",
        "En el foro tienes que expresar tu opinión con respeto y respaldarla con al menos un ejemplo.",
        "在论坛讨论中你需要礼貌地表达观点，并至少用一个例子支撑。",
        "讨论会上举手发言的学生，桌上有意见卡片",
    ),
    (
        "argumento",
        1,
        "m",
        "B1",
        "论据；论点",
        "Un buen argumento conecta hechos verificables con una conclusión lógica y fácil de seguir.",
        "好的论据把可核实的事实与易于跟随的逻辑结论联系起来。",
        "思维导图连接「事实→推理→结论」，风格简洁教育风",
    ),
    (
        "definición",
        1,
        "f",
        "B1",
        "定义",
        "Antes de discutir el concepto, conviene recordar la definición del diccionario y un ejemplo real.",
        "讨论概念之前，最好先回顾词典定义和一个真实例子。",
        "打开的词典与便利贴上写出「定义」与例句示意（无具体字母乱码）",
    ),
    (
        "contexto",
        1,
        "m",
        "B1",
        "上下文；语境",
        "Sin contexto, una palabra puede tener varios sentidos; por eso siempre leemos la frase completa.",
        "没有语境时一个词可能有多种意思，所以我们总是读完整句话。",
        "一段高亮句子框出关键词，周围词语以淡色表示上下文",
    ),
    (
        "comprensión",
        1,
        "f",
        "B1",
        "理解（阅读/听力）",
        "La comprensión lectora mejora si subrayas ideas principales y vuelves a decirlas con tus palabras.",
        "若能划出主要意思并用自己的话复述，阅读理解会提高。",
        "学生阅读文本并用荧光笔标出关键句",
    ),
    (
        "expresión",
        1,
        "f",
        "B1",
        "表达；固定表达",
        "Aprendí una expresión muy útil: «estar hecho polvo», que significa estar muy cansado.",
        "我学到一个很有用的表达：estar hecho polvo，意思是筋疲力尽。",
        "对话框里出现一句生动口语表达，旁边用图标表示「很累」",
    ),
    (
        "sinónimo",
        1,
        "m",
        "B1",
        "同义词",
        "Busca un sinónimo más formal de «cosa» cuando escribas un texto académico, por ejemplo «elemento».",
        "写学术文本时，给「cosa」找一个更正式的同义词，例如「elemento」。",
        "两个含义相近的词用双向箭头连接，风格词典插图",
    ),
    (
        "antónimo",
        1,
        "m",
        "B1",
        "反义词",
        "El antónimo de «temprano» es «tarde»; practicar antonimos ayuda a organizar el vocabulario.",
        "temprano 的反义词是 tarde；练习反义词有助于整理词汇。",
        "左右对称图标：太阳（早）与月亮（晚）相对",
    ),
    (
        "falso amigo",
        1,
        "m",
        "B1",
        "假朋友词（形似义不同）",
        "«Embarazada» es un falso amigo famoso: no significa «avergonzada», sino «pregnant».",
        "embarazada 是个著名的假朋友词：不是「尴尬」，而是「怀孕」。",
        "两个看起来相似却指向不同含义的词汇纸牌，中间画叉以示勿混",
    ),
    (
        "registro",
        1,
        "m",
        "B1",
        "语体；语域",
        "En un correo al profesor conviene un registro más formal que en un mensaje a un amigo.",
        "给老师发邮件时，语体应比发给朋友的消息更加正式。",
        "并排两只手机/邮件界面：一正式一轻松（界面无具体可读文字）",
    ),
    (
        "oral",
        1,
        "adj",
        "A2",
        "口头的",
        "La prueba oral dura diez minutos: presentas un tema y luego respondes preguntas del examinador.",
        "口语考试约十分钟：先就一个主题发言，再回答考官提问。",
        "考官与考生面对面进行口语测试，桌上有计时器",
    ),
    (
        "escrito",
        1,
        "adj",
        "A2",
        "书面的",
        "El examen escrito evalúa ortografía, coherencia y el uso correcto de conectores.",
        "笔试考查拼写、连贯性与连接词的正确使用。",
        "学生在考卷发上一篇作文，旁边放着橡皮与笔",
    ),
    (
        "puntuación",
        1,
        "f",
        "B1",
        "标点；得分",
        "La puntuación correcta —comas, puntos y signos de interrogación— hace el texto más claro.",
        "正确的标点——逗号、句号和问号——能让文章更清晰。",
        "放大的句子中突出逗号与问号等标点符号的插画",
    ),
    (
        "ortografía",
        1,
        "f",
        "B1",
        "拼写",
        "Cuidar la ortografía incluye tildes y la diferencia entre b/v o g/j según la regla.",
        "注意拼写包括重音符号，以及按规则区分 b/v、g/j 等。",
        "单词上方正确标注重音符号，错误拼写被轻轻划掉",
    ),
    (
        "acento",
        1,
        "m",
        "A2",
        "重音；（书面）尖音符",
        "En español el acento gráfico marca la sílaba tónica, como en «café» o «información».",
        "西语里尖音符标出重读音节，例如 café 或 información。",
        "单词音节划分并突出重读音节与尖音符",
    ),
    (
        "nivel",
        1,
        "m",
        "A2",
        "水平；等级",
        "Mi nivel de español es B1: puedo desenvolverme en viajes y entender textos cotidianos.",
        "我的西语水平是 B1：能应对旅行场景并理解日常文本。",
        "阶梯状等级示意图从低到高，人物站在中间一级",
    ),
    (
        "progreso",
        1,
        "m",
        "B1",
        "进步；进展",
        "Registrar tu progreso cada semana motiva a seguir practicando aunque avances poco a poco.",
        "每周记录进步，即使进步很小也能激励你继续练习。",
        "增长曲线图与打卡日历，旁边有学习勾选清单",
    ),
    (
        "objetivo",
        1,
        "m",
        "B1",
        "目标",
        "Mi objetivo este mes es aprender cincuenta palabras nuevas y usarlas en oraciones propias.",
        "我这个月的目标是学会五十个新词，并用它们造出自己的句子。",
        "箭靶中央命中，周围环绕单词卡片与小旗帜",
    ),
    (
        "estrategia",
        1,
        "f",
        "B1",
        "策略",
        "Una buena estrategia de lectura es leer primero el título y los subtítulos antes del texto.",
        "很好的阅读策略是先看标题与小标题，再读正文。",
        "学生先看目录式标题再打开正文，步骤用 1-2-3 小图标表示",
    ),
    (
        "recurso",
        1,
        "m",
        "B1",
        "资源",
        "Los podcasts y vídeos subtitulados son recursos excelentes para mejorar la comprensión auditiva.",
        "播客与带字幕视频是提高听力理解的绝佳资源。",
        "耳机、平板电脑与笔记本组成的学习资源静物",
    ),
    (
        "diccionario",
        1,
        "m",
        "A2",
        "词典",
        "Cuando dudes del sentido, consulta un diccionario bilingüe y también un ejemplo en contexto.",
        "对词义不确定时，查双语词典并看一个语境例句。",
        "翻开厚词典的特写，书签夹在词条页",
    ),
    (
        "facultad",
        1,
        "f",
        "B1",
        "（大学）学院",
        "Estudio en la facultad de lenguas extranjeras y mi especialidad es la lengua española.",
        "我在外国语学院学习，专业是西班牙语。",
        "大学学院楼前学生们走过，门楣有抽象校徽（无文字）",
    ),
    (
        "especialidad",
        1,
        "f",
        "B1",
        "专业",
        "Mi especialidad combina lingüística aplicada con estudios culturales del mundo hispánico.",
        "我的专业把应用语言学与西语世界文化研究结合在一起。",
        "书架上语言与文化类书籍，桌上有地球仪指向西语地区",
    ),
    (
        "credencial",
        1,
        "f",
        "B1",
        "证件；学生证",
        "Con la credencial de estudiante puedes entrar a la biblioteca y obtener descuentos en museos.",
        "凭学生证可以进图书馆，并在博物馆享有折扣。",
        "手持学生证卡片，背景是图书馆入口",
    ),
    (
        "beca",
        1,
        "f",
        "B1",
        "奖学金",
        "Solicité una beca de intercambio para estudiar un semestre en una universidad de Madrid.",
        "我申请了交换奖学金，希望去马德里某大学读一学期。",
        "奖学金信封与录取通知意象，背景有大学建筑剪影",
    ),
    (
        "intercambio académico",
        1,
        "m",
        "B1",
        "学术交流；交换学习",
        "Durante el intercambio académico viví con una familia anfitriona y asistí a clases locales.",
        "学术交换期间我住在接待家庭，并上当地的课程。",
        "行李箱、护照与校园钥匙，象征出国交换",
    ),
    (
        "hospedaje",
        1,
        "m",
        "B1",
        "住宿",
        "El hospedaje en residencia universitaria sale más barato que alquilar un piso completo.",
        "住在大学宿舍通常比整租一套公寓更便宜。",
        "简洁学生宿舍内景：床、书桌与小窗",
    ),
    (
        "alquilar",
        1,
        "v",
        "B1",
        "租借；租赁",
        "Vamos a alquilar un piso cerca del metro para ahorrar tiempo en el trayecto a la facultad.",
        "我们打算在地铁附近租房，以节省去学院路上的时间。",
        "中介钥匙交给租客，背景是公寓楼外观",
    ),
    (
        "presupuesto",
        1,
        "m",
        "B1",
        "预算",
        "Haz un presupuesto mensual: comida, transporte, material de estudio y un pequeño ahorro.",
        "做一份月预算：吃饭、交通、学习用品和一点储蓄。",
        "笔记本上分类账目与硬币、计算器的静物构图",
    ),
    (
        "trámites",
        1,
        "m",
        "B1",
        "手续（常用复数）",
        "Los trámites de visado exigen pasaporte, carta de admisión y prueba de fondos económicos.",
        "签证手续需要护照、录取信和经济能力证明。",
        "文件袋、表格与印章图标排成办事流程",
    ),
    (
        "cita",
        1,
        "f",
        "A2",
        "预约；（也指）约会",
        "Pedí una cita en la oficina de extranjeros para renovar mi tarjeta de residencia.",
        "我预约了外国人事务办公室去续居留卡。",
        "行政窗口叫号屏幕与拿号票的学生",
    ),
    (
        "cita",
        2,
        "f",
        "B1",
        "引文；引用",
        "En el trabajo académico debes incluir la cita correcta para no plagiar las ideas ajenas.",
        "学术作业必须正确引用，以免剽窃他人观点。",
        "论文脚注区域特写，引号与参考文献卡片",
    ),
    (
        "plagio",
        1,
        "m",
        "B1",
        "剽窃",
        "Copiar párrafos sin indicar la fuente se considera plagio y puede anular el trabajo.",
        "不标注出处就抄写段落属于剽窃，可能导致作业作废。",
        "两页文本高度雷同被放大镜标出，警示教育插画（非恐吓）",
    ),
]

TEM8: list[tuple] = [
    (
        "hipótesis",
        1,
        "f",
        "B2",
        "假设；假说",
        "La hipótesis del estudio sostiene que el contacto frecuente con hablantes nativos acelera la fluidez.",
        "该研究假设：与母语者频繁接触会加快流利度提升。",
        "实验室或研究场景中，白板上写着「假设—验证」流程图（无具体文字）",
    ),
    (
        "metodología",
        1,
        "f",
        "B2",
        "方法论；方法",
        "La metodología combina análisis cuantitativo de corpus y entrevistas cualitativas a aprendices.",
        "该方法论结合语料库定量分析与对学习者的定性访谈。",
        "研究者在电脑前分析数据图表，旁边有访谈录音设备",
    ),
    (
        "análisis",
        1,
        "m",
        "B2",
        "分析",
        "El análisis del discurso revela cómo los conectores organizan la argumentación en un editorial.",
        "话语分析揭示连接词如何在社论中组织论证结构。",
        "放大镜对准文章结构图：引言、论据与结论分层",
    ),
    (
        "discurso",
        1,
        "m",
        "B2",
        "话语；演说",
        "El discurso político usa metáforas y repeticiones para persuadir a una audiencia diversa.",
        "政治演说运用隐喻与重复，以说服多元听众。",
        "讲台上演讲者面对观众，灯光聚焦但无政治标志",
    ),
    (
        "narrativa",
        1,
        "f",
        "B2",
        "叙事；叙事作品",
        "En la narrativa contemporánea el narrador a veces es poco fiable y obliga al lector a interpretar.",
        "在当代叙事中，叙述者有时不可靠，迫使读者自行解读。",
        "打开的小说与交错时间线丝带，象征叙事结构",
    ),
    (
        "metáfora",
        1,
        "f",
        "B2",
        "隐喻",
        "La metáfora «el tiempo es oro» presenta el tiempo como un recurso valioso que no debe malgastarse.",
        "隐喻「时间就是金钱」把时间呈现为不应浪费的宝贵资源。",
        "沙漏与金币意象巧妙融合，表现隐喻概念",
    ),
    (
        "ironía",
        1,
        "f",
        "B2",
        "反讽；讽刺",
        "La ironía del personaje aparece cuando dice lo contrario de lo que realmente piensa.",
        "当人物说的与真实想法相反时，反讽便出现了。",
        "笑脸面具下露出相反表情，轻喜剧教育插画风格",
    ),
    (
        "ambigüedad",
        1,
        "f",
        "C1",
        "歧义；含混",
        "La ambigüedad deliberada en el poema permite varias lecturas sin una interpretación única.",
        "诗中故意的含混允许多种解读，而非单一解释。",
        "一幅画面可看成两种图形的视错觉插画，象征歧义",
    ),
    (
        "coherencia",
        1,
        "f",
        "B2",
        "连贯；条理",
        "La coherencia textual depende de que cada párrafo avance la idea central sin contradicciones.",
        "篇章连贯取决于每一段推进中心思想且不自相矛盾。",
        "环环相扣的链条连接各段落方块，象征连贯",
    ),
    (
        "cohesión",
        1,
        "f",
        "B2",
        "衔接（语言学术语）",
        "Los pronombres y los conectores aportan cohesión al unir oraciones dentro del mismo párrafo.",
        "代词与连接词通过把句间关系连起来，带来篇章衔接。",
        "句子块被彩色纽带轻轻连接，学术示意图风格",
    ),
    (
        "inferencia",
        1,
        "f",
        "B2",
        "推断；推理",
        "Aunque el texto no lo diga explícitamente, por inferencia entendemos que el personaje está en crisis.",
        "虽然文本未明说，通过推断我们明白人物正陷入危机。",
        "侦探式拼图：线索卡片指向一个结论灯泡",
    ),
    (
        "implicatura",
        1,
        "f",
        "C1",
        "会话含义（语用学）",
        "La implicatura surge cuando el oyente deduce un sentido no dicho a partir del contexto conversacional.",
        "当听者根据会话语境推出未明说的含义时，便产生会话含义。",
        "两人对话气泡：显说内容与虚线「言外之意」",
    ),
    (
        "pragmatismo",
        1,
        "m",
        "C1",
        "实用主义；（亦指）务实态度",
        "Con pragmatismo, la institución eligió un plan viable en lugar de una reforma ideal pero imposible.",
        "出于务实，该机构选择了可行方案，而非理想却不可行的改革。",
        "天平一端「理想蓝图」一端「可行方案」，指针偏向可行",
    ),
    (
        "ideología",
        1,
        "f",
        "C1",
        "意识形态",
        "El ensayo examina cómo la ideología se infiltra en las elecciones léxicas de un texto periodístico.",
        "这篇文章检视意识形态如何渗透进新闻文本的用词选择。",
        "报刊版面背后隐约的抽象色块层，象征观念影响（无政治符号）",
    ),
    (
        "hegemonía",
        1,
        "f",
        "C1",
        "霸权；主导地位",
        "Algunos autores hablan de hegemonía cultural cuando ciertos relatos dominan el espacio mediático.",
        "某些作者称，当特定叙事主导媒体空间时，便存在文化霸权。",
        "大型聚光灯照亮舞台中央，边缘人物处在阴影中",
    ),
    (
        "perspectiva",
        1,
        "f",
        "B2",
        "视角；观点",
        "Cambiar de perspectiva nos hace ver el conflicto desde el lado de las personas afectadas.",
        "转换视角能让我们从受影响者一方去看这场冲突。",
        "同一景物被两扇不同颜色的窗传来，象征视角差异",
    ),
    (
        "enfoque",
        1,
        "m",
        "B2",
        "切入角度；方法焦点",
        "El enfoque comunicativo prioriza el uso real de la lengua frente a la memorización de reglas.",
        "交际法优先真实使用语言，而非死记规则。",
        "镜头对焦清晰主体、背景虚化，隐喻「聚焦」",
    ),
    (
        "paradigma",
        1,
        "m",
        "C1",
        "范式",
        "El nuevo paradigma educativo pone al estudiante como centro del proceso de aprendizaje.",
        "新的教育范式把学生置于学习过程的中心。",
        "旧齿轮切换为新齿轮的转换意象，象征范式更替",
    ),
    (
        "crítica",
        1,
        "f",
        "B2",
        "评论；批评",
        "La crítica literaria no solo juzga si un libro «gusta», sino cómo construye sentido y estilo.",
        "文学批评不只判断书是否「好看」，还分析它如何构建意义与风格。",
        "书评家在咖啡馆批注打开的小说书页",
    ),
    (
        "reseña",
        1,
        "f",
        "B2",
        "书评；简介性评论",
        "La reseña resume la trama sin spoilers y valora el ritmo, los personajes y el lenguaje.",
        "书评概括情节但不剧透，并评价节奏、人物与语言。",
        "书旁边贴着简短评星卡片（星标图标、无文字）",
    ),
    (
        "intertextualidad",
        1,
        "f",
        "C1",
        "互文性",
        "La intertextualidad aparece cuando la novela cita, transforma o dialoga con obras anteriores.",
        "当小说引用、改写或与先前作品对话时，便出现互文性。",
        "多本书页面彼此交叠、箭头连接，象征文本对话",
    ),
    (
        "alegoría",
        1,
        "f",
        "C1",
        "寓言；讽喻",
        "En la alegoría cada elemento del relato representa una idea abstracta sobre la sociedad.",
        "在寓言/讽喻中，故事里每个元素都象征某种关于社会的抽象观念。",
        "看似童话场景，细节却映射现实结构的多层插画",
    ),
    (
        "simbolismo",
        1,
        "m",
        "C1",
        "象征手法；象征主义",
        "El simbolismo del río en la novela sugiere transformación y el paso irreversible del tiempo.",
        "小说中河流的象征暗示转变与时间的不可逆流逝。",
        "河流光影中隐现时钟与变形轮廓，诗意插画",
    ),
    (
        "estilo",
        1,
        "m",
        "B2",
        "风格；文风",
        "El estilo del autor se reconoce por frases largas, adjetivos precisos y un humor contenido.",
        "作者的文风以长句、精确形容词与克制的幽默为特征。",
        "羽毛笔在纸上留下鲜明个性的笔迹曲线",
    ),
    (
        "registro académico",
        1,
        "m",
        "B2",
        "学术语体",
        "En el registro académico evitamos muletillas y preferimos conectores como «por consiguiente».",
        "学术语体中我们避免口头禅，更偏好「因此」一类连接词。",
        "正式论文版式示意与研究图标，氛围沉静专业",
    ),
    (
        "terminología",
        1,
        "f",
        "B2",
        "术语",
        "Dominar la terminología especializada es necesario para leer artículos científicos con precisión.",
        "要精确阅读科研文章，必须掌握专业术语。",
        "术语卡片贴在白板上，配有简明图标注解",
    ),
    (
        "corpus",
        1,
        "m",
        "C1",
        "语料库",
        "El corpus digital permite observar frecuencias reales de uso y colocaciones frecuentes.",
        "数字语料库能观察真实使用频率与常见搭配。",
        "服务器与文档数据流汇入分析屏幕的抽象示意图",
    ),
    (
        "colocación",
        1,
        "f",
        "C1",
        "搭配（词汇学）",
        "Es más natural decir «tomar una decisión» que «hacer una decisión»; eso es una colocación.",
        "说 tomar una decisión 比 hacer una decisión 更自然，这就是搭配。",
        "两块磁石吸住两个固定搭配的词块",
    ),
    (
        "polisemia",
        1,
        "f",
        "C1",
        "多义性",
        "La polisemia de «banco» incluye el asiento y la institución financiera según el contexto.",
        "banco 的多义性包括「长凳」与「银行」，取决于语境。",
        "同一词根分出两条路径指向长凳与银行建筑",
    ),
    (
        "homónimo",
        1,
        "m",
        "B2",
        "同音/同形异义词",
        "«Banco» (asiento) y «banco» (entidad financiera) son homónimos: misma forma, sentidos distintos.",
        "banco（长凳）与 banco（金融机构）是同形异义词：形式相同、意义不同。",
        "两张词卡字形相同但画面意象完全不同：长凳与银行",
    ),
    (
        "etimología",
        1,
        "f",
        "C1",
        "词源",
        "La etimología de muchas palabras españolas remonta al latín y, en algunos casos, al árabe.",
        "许多西语词的词源可追溯到拉丁语，有些则来自阿拉伯语。",
        "词根树：古语树根生长出现代西语词叶",
    ),
    (
        "préstamo lingüístico",
        1,
        "m",
        "C1",
        "借词",
        "«Fútbol» es un préstamo lingüístico del inglés que se ha adaptado a la ortografía española.",
        "fútbol 是来自英语的借词，并已适应西语拼写。",
        "单词跨越国境线「迁移」的轻快插画",
    ),
    (
        "variedad dialectal",
        1,
        "f",
        "C1",
        "方言变体",
        "La variedad dialectal del español de México difiere en léxico y entonación del español de España.",
        "墨西哥西语方言变体在词汇与语调上与西班牙西语有所不同。",
        "地图上两个西语地区用不同色温区分，中间是对话示意",
    ),
    (
        "sociolingüística",
        1,
        "f",
        "C1",
        "社会语言学",
        "La sociolingüística estudia cómo la clase social, la edad y el género influyen en el habla.",
        "社会语言学研究社会阶层、年龄与性别如何影响言语。",
        "城市人群剪影与语言波形交织的学术插画",
    ),
    (
        "bilingüismo",
        1,
        "m",
        "B2",
        "双语能力；双语现象",
        "El bilingüismo no implica dominio perfecto de ambas lenguas en todos los registros.",
        "双语并不意味着两种语言在一切语体上都完美精通。",
        "大脑左右象征两种语言和谐共存的简洁插画",
    ),
    (
        "competencia",
        1,
        "f",
        "B2",
        "能力；（语言）能力",
        "La competencia comunicativa incluye saber qué decir, cómo decirlo y cuándo callar.",
        "交际能力包括知道说什么、怎么说，以及何时保持沉默。",
        "人物在不同社交场景切换得体表达的三联画",
    ),
    (
        "competencia",
        2,
        "f",
        "B2",
        "竞争；竞赛",
        "La competencia entre empresas tecnológicas acelera la innovación, pero también genera presión laboral.",
        "科技企业间的竞争加速创新，但也带来职场压力。",
        "两条赛道上的奔跑者象征市场竞争，非攻击性表现",
    ),
    (
        "innovación",
        1,
        "f",
        "B2",
        "创新",
        "La innovación educativa no es solo usar apps, sino rediseñar actividades para un aprendizaje activo.",
        "教育创新不只是用 App，而是重新设计活动以促进主动学习。",
        "灯泡与齿轮结合，周围是课堂协作小组",
    ),
    (
        "sostenibilidad",
        1,
        "f",
        "B2",
        "可持续性",
        "La sostenibilidad urbana exige transporte público eficiente y espacios verdes accesibles.",
        "城市可持续性要求高效公交与市民可达的绿色空间。",
        "绿色屋顶城市与自行车道、太阳能板的和谐景象",
    ),
    (
        "globalización",
        1,
        "f",
        "B2",
        "全球化",
        "La globalización facilita el intercambio cultural, aunque también plantea retos a las identidades locales.",
        "全球化促进文化交流，同时也给地方认同带来挑战。",
        "地球网格连接多个城市光点，柔和而非冷冰冰",
    ),
    (
        "migración",
        1,
        "f",
        "B2",
        "移民；迁徙",
        "La migración por estudios es común entre universitarios que buscan experiencias internacionales.",
        "出于求学原因的迁移在寻求国际体验的大学生中很常见。",
        "年轻人背着背包站在机场落地窗前望向新城市",
    ),
    (
        "identidad",
        1,
        "f",
        "B2",
        "身份；认同",
        "La identidad cultural se construye con la lengua, la memoria familiar y las prácticas cotidianas.",
        "文化认同由语言、家庭记忆与日常实践共同建构。",
        "人物剪影由多元文化纹理拼贴而成，温暖尊重",
    ),
    (
        "diversidad",
        1,
        "f",
        "B2",
        "多样性",
        "La diversidad lingüística del mundo hispánico es un patrimonio que conviene preservar y estudiar.",
        "西语世界的语言多样性是值得保护与研究的遗产。",
        "多彩丝带编织成一张网，象征多元共存",
    ),
    (
        "patrimonio",
        1,
        "m",
        "B2",
        "遗产（文化）",
        "El patrimonio inmaterial incluye danzas, oficios y saberes transmitidos de generación en generación.",
        "非物质文化遗产包括代代相传的舞蹈、手艺与知识。",
        "传统手工艺人向年轻人传授技艺的温馨场景",
    ),
    (
        "memoria histórica",
        1,
        "f",
        "C1",
        "历史记忆",
        "El debate sobre la memoria histórica examina cómo una sociedad recuerda conflictos del pasado.",
        "关于历史记忆的讨论审视一个社会如何铭记过去的冲突。",
        "档案馆与老照片相册被当代青年翻阅（无具体政治人物）",
    ),
    (
        "ética",
        1,
        "f",
        "B2",
        "伦理",
        "La ética periodística exige verificar fuentes antes de publicar una acusación grave.",
        "新闻伦理要求在刊发严重指控前核实消息来源。",
        "天平与报纸结合的简洁象征，强调核实与责任",
    ),
    (
        "sesgo",
        1,
        "m",
        "C1",
        "偏见；偏差",
        "Detectar el sesgo en un artículo implica observar qué voces se citan y cuáles se omiten.",
        "识别文章中的偏见，要看引用了哪些声音、又忽略了哪些。",
        "倾斜的天平与放大镜检视新闻剪报",
    ),
    (
        "fuente",
        1,
        "f",
        "B2",
        "来源；（也指）泉水",
        "Cita siempre la fuente primaria cuando uses datos estadísticos en tu trabajo de investigación.",
        "在研究作业中使用统计数据时，务必引用原始来源。",
        "文献卡片指向原始数据报告的引用链条示意",
    ),
    (
        "fuente",
        2,
        "f",
        "B2",
        "泉水；喷泉",
        "Nos sentamos junto a la fuente de la plaza mientras repasábamos las preguntas del examen oral.",
        "我们坐在广场喷泉旁复习口语考试的问题。",
        "阳光下的城市广场喷泉，周围有石凳与鸽子",
    ),
    (
        "tesis",
        1,
        "f",
        "B2",
        "论点；（亦指）学位论文",
        "La tesis del artículo afirma que el subtitulado favorece el aprendizaje incidental de vocabulario.",
        "文章的论点是：字幕有利于词汇的附带习得。",
        "论文封面与核心论断卡片被钉在研究板上",
    ),
    (
        "tesis",
        2,
        "f",
        "C1",
        "学位论文",
        "Defendió su tesis doctoral ante un tribunal tras cinco años de investigación de archivo.",
        "经过五年档案研究，她在答辩委员会前进行了博士论文答辩。",
        "答辩教室里候选人答辩、委员提问的正式场景",
    ),
    (
        "abstract",
        1,
        "m",
        "C1",
        "摘要（学术论文）",
        "El abstract debe condensar objetivos, método, resultados y conclusión en un párrafo denso.",
        "摘要需在紧凑一段中概括目标、方法、结果与结论。",
        "论文首页顶部的摘要区块被高亮框出",
    ),
    (
        "conclusión",
        1,
        "f",
        "B2",
        "结论",
        "En la conclusión no introduzcas datos nuevos; resume y señala límites o futuras líneas de trabajo.",
        "结论部分不要引入新数据；应总结并指出局限或未来研究方向。",
        "通往山顶旗帜的小路，象征得出结论",
    ),
    (
        "matiz",
        1,
        "m",
        "C1",
        "细微差别；语感差别",
        "Hay un matiz importante entre «pedir» y «solicitar»: el segundo suele ser más formal.",
        "pedir 与 solicitar 有重要细微差别：后者通常更正式。",
        "色阶色卡显示细微色差，隐喻词语的语感差别",
    ),
    (
        "precisión",
        1,
        "f",
        "B2",
        "精确；精准",
        "La precisión léxica distingue a un texto avanzado de una redacción solo «comprensible».",
        "词汇精确度把高级文本与仅仅「能看懂」的作文区分开。",
        "游标卡尺般精确对齐词义天平的插画",
    ),
    (
        "concisión",
        1,
        "f",
        "C1",
        "简洁",
        "La concisión no significa empobrecer el estilo, sino eliminar repeticiones innecesarias.",
        "简洁并不意味着风格贫乏，而是去掉不必要的重复。",
        "冗长段落被精炼成短句的前后对比示意",
    ),
    (
        "redundancia",
        1,
        "f",
        "C1",
        "冗余；重复累赘",
        "Evita la redundancia del tipo «subir hacia arriba»; una sola idea basta si ya está clara.",
        "避免「向上爬升」这类冗余；意思已清楚时说一遍即可。",
        "堆叠重复方块被删减编辑，留下精简结构",
    ),
    (
        "eufemismo",
        1,
        "m",
        "C1",
        "委婉语",
        "Decir «tercer edad» en lugar de expresiones peyorativas es un eufemismo social común.",
        "用「terce edad / 老年」替代贬损说法，是常见的社会委婉语。",
        "尖锐词语被软布轻轻裹住的象征插画，温和教育风",
    ),
    (
        "tabú lingüístico",
        1,
        "m",
        "C1",
        "语言禁忌",
        "El tabú lingüístico explica por qué ciertas palabras se evitan en contextos formales o familiares.",
        "语言禁忌解释了为何某些词在正式或家庭语境中会被回避。",
        "嘴唇前竖起安静手势，背景词语淡出，非恐吓表现",
    ),
]


def image_name(lemma: str, sense: int) -> str:
    slug = (
        lemma.lower()
        .replace("á", "a")
        .replace("é", "e")
        .replace("í", "i")
        .replace("ó", "o")
        .replace("ú", "u")
        .replace("ü", "u")
        .replace("ñ", "n")
        .replace(" ", "_")
    )
    slug = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in slug)
    return f"images/{slug}_{sense}.png"


def rows_from(items: list[tuple]) -> list[list]:
    out = []
    for lemma, sense, cat, level, zh, es, zh_ex, scene in items:
        out.append(
            [
                lemma,
                sense,
                cat,
                level,
                zh,
                es,
                zh_ex,
                image_name(lemma, sense),
                prompt(scene),
            ]
        )
    return out


def style_header(ws) -> None:
    fill = PatternFill("solid", fgColor="1F4E79")
    font = Font(color="FFFFFF", bold=True)
    for col, h in enumerate(HEADERS, 1):
        cell = ws.cell(1, col, h)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(wrap_text=True, vertical="center")
    ws.freeze_panes = "A2"
    widths = [22, 8, 12, 8, 22, 56, 40, 28, 70]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def write_sheet(wb: Workbook, title: str, items: list[tuple]) -> None:
    ws = wb.create_sheet(title)
    style_header(ws)
    for r, row in enumerate(rows_from(items), 2):
        for c, val in enumerate(row, 1):
            cell = ws.cell(r, c, val)
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    ws.row_dimensions[1].height = 22


def write_guide(wb: Workbook) -> None:
    ws = wb.create_sheet("说明", 0)
    ws["A1"] = "专四 / 专八义项表 · 使用说明（对齐 senses_table 格式）"
    ws["A1"].font = Font(bold=True, size=14, color="1F4E79")
    lines = [
        "",
        "【格式】与 senses_table.xlsx 相同列：西语 / 义项 / categoría / 级别 / 中文释义 / 例句*西语 / 例句*中文 / 图片",
        "额外增加一列「配图提示词」，方便同学 B 直接用于 AI 绘图或手绘创作说明。",
        "",
        "【categoría】f=阴性名词 m=阳性名词 v=动词 adj=形容词 adv=副词 …",
        "【级别】专四表以 A2–B1 为主；专八表以 B2–C1 为主（便于与 App DELE 等级对齐）。",
        "【图片】填写相对路径占位，如 images/ensayo_1.png；同学 B 出图后可内嵌或交技术导入。",
        "",
        "【配图风格统一要求】",
        "教育插画 · 正方形 1:1 · 明亮柔和 · 单一主体 · 浅色背景 · 无文字/水印/logo",
        "建议尺寸：800×800（与现有 A1 配图一致）。",
        "",
        "【同学分工】",
        "同学 A：校对中文释义与例句；可增删义项；多义词分行（义项 1、2…）。",
        "同学 B：按「配图提示词」出图，文件名与「图片」列一致。",
        "技术：导入时可参考 scripts/import_senses_xlsx.py（需扩展 exam_tags=专四/专八）。",
        "",
        f"【本版数量】专四 {len(TEM4)} 义项 · 专八 {len(TEM8)} 义项（示范稿，可继续扩充）。",
        "本表不与线上 A1 义项包冲突：考试路径可单独维护后导入。",
    ]
    for i, line in enumerate(lines, 2):
        ws.cell(i, 1, line)
    ws.column_dimensions["A"].width = 110


def save_book(path: Path, items: list[tuple] | None, sheet: str | None, combined: bool) -> None:
    wb = Workbook()
    # remove default
    default = wb.active
    wb.remove(default)
    if combined:
        write_guide(wb)
        write_sheet(wb, "专四", TEM4)
        write_sheet(wb, "专八", TEM8)
    else:
        assert items is not None and sheet is not None
        write_sheet(wb, sheet, items)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    print(f"Wrote {path} ({path.stat().st_size} bytes)")


def main() -> None:
    save_book(OUT_DIR / "senses_table_tem4.xlsx", TEM4, "专四", combined=False)
    save_book(OUT_DIR / "senses_table_tem8.xlsx", TEM8, "专八", combined=False)
    save_book(OUT_DIR / "senses_table_exams.xlsx", None, None, combined=True)

    # also export prompts-only CSV for quick copy
    import csv

    for name, items in (("tem4", TEM4), ("tem8", TEM8)):
        csv_path = OUT_DIR / f"image_prompts_{name}.csv"
        with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
            w = csv.writer(f)
            w.writerow(["西语", "义项", "中文释义", "图片文件名", "配图提示词"])
            for lemma, sense, _cat, _level, zh, _es, _zh_ex, scene in items:
                w.writerow([lemma, sense, zh, image_name(lemma, sense), prompt(scene)])
        print(f"Wrote {csv_path}")


if __name__ == "__main__":
    main()
